// @author		Giacomo Marton
// @version		1.0.0



///Constants definition for GMMath

//Assimp Post Process
// Feather disable GM1003
enum GMA_PP
{
	CALC_TANGENT_SPACE			= 0x1,
	JOIN_IDENTICAL_VERTICES		= 0x2,
	MAKE_LEFT_HANDED			= 0x4,
	TRIANGULATE					= 0x8,
	REMOVE_COMPONENT			= 0x10,
	GEN_NORMALS					= 0x20,
	GEN_SMOOTH_NORMALS			= 0x40,
	SPLIT_LARGE_MESHES			= 0x80,
	PRETRANSFORM_VERTICES		= 0x100,
	LIMIT_BONE_WEIGHTS			= 0x200,
	VALIDATE_DATA_STRUCTURE		= 0x400,
	IMPROVE_CACHE_LOCALITY		= 0x800,
	REMOVE_REDUNDANT_MATERIALS = 0x1000,
	FIX_INFACING_NORMALS		= 0x2000,
	POPULATE_ARMATURE_DATA		= 0x4000,
	SORT_BY_PTYPE				= 0x8000,
	FIND_DEGENERATES			= 0x10000,
	FIND_INVALID_DATA			= 0x20000,
	GEN_UV_COORDS				= 0x40000,
	TRANSFORM_UV_COORDS			= 0x80000,
	FIND_INSTANCES				= 0x100000,
	OPTIMIZE_MESHES				= 0x200000,
	OPTIMIZE_GRAPH				= 0x400000,
	FLIP_UVS					= 0x800000,
	FLIP_WINDING_ORDER			= 0x1000000,
	SPLIT_BONE_COUNT			= 0x2000000,
	DEBONE						= 0x4000000,
	GLOBAL_SCALE				= 0x8000000,
	EMBED_TEXTURES				= 0x10000000,
	FORCE_GEN_NORMALS			= 0x20000000,
	DROP_NORMALS				= 0x40000000,
	GEN_BOUNDING_BOXES			= 0x80000000,
	CONVERT_TO_LEFT_HANDED		= GMA_PP.MAKE_LEFT_HANDED | GMA_PP.FLIP_UVS | GMA_PP.FLIP_WINDING_ORDER,
	TARGET_REALTIME_FAST		= GMA_PP.CALC_TANGENT_SPACE | GMA_PP.GEN_NORMALS | GMA_PP.JOIN_IDENTICAL_VERTICES | GMA_PP.TRIANGULATE | GMA_PP.GEN_UV_COORDS | GMA_PP.SORT_BY_PTYPE,
	TARGET_REALTIME_QUALITY		= GMA_PP.CALC_TANGENT_SPACE | GMA_PP.GEN_SMOOTH_NORMALS | GMA_PP.JOIN_IDENTICAL_VERTICES | GMA_PP.IMPROVE_CACHE_LOCALITY | GMA_PP.LIMIT_BONE_WEIGHTS | GMA_PP.REMOVE_REDUNDANT_MATERIALS | GMA_PP.SPLIT_LARGE_MESHES | GMA_PP.TRIANGULATE | GMA_PP.GEN_UV_COORDS | GMA_PP.SORT_BY_PTYPE | GMA_PP.FIND_DEGENERATES | GMA_PP.FIND_INVALID_DATA,
	TARGET_REALTIME_MAX_QUALITY	= GMA_PP.TARGET_REALTIME_QUALITY | GMA_PP.FIND_INSTANCES | GMA_PP.VALIDATE_DATA_STRUCTURE | GMA_PP.OPTIMIZE_MESHES | GMA_PP.DEBONE
}
